### ISSUE TITLE
Changing the reason for the record that previously had tool changeover, affects the parent record

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#1]
When:
I change the reason for the record that has tool changover.

Then:
It should change the reason, tool name, part name of the succeeding records (child record) to the data that they had prior to the tool changeover.

Actual:
It doesnt change the reason, tool name, part name of the succeeding records and also changes the tool name and part name of the parernt record

![Screenshot (331)](https://user-images.githubusercontent.com/118270248/204095685-0b6dbc6c-4a91-4716-ae95-b946b53a47cd.png)
![Screenshot (332)](https://user-images.githubusercontent.com/118270248/204095816-fd878113-b6ee-440c-9eaa-0f7adb321399.png)

**Comment by tamizh061** [comment]
![image](https://user-images.githubusercontent.com/118597994/207539203-b98055da-7815-4f87-a8c3-a9aa4b40e13d.png)
![image](https://user-images.githubusercontent.com/118597994/207539310-9eafa67d-d153-4acc-9e6f-6c8f21ef76f9.png)
