### ISSUE TITLE
financial metrics from date to  date shows seconds in the selected option

### ISSUE THREAD

**Issue by tamizh061** [SmartMach/webapp-v1#38]
when
selecting  the from date and  to date in  financial metrics
then
seconds   no need to show  time selection in financial metrics
actual 
it shown as 09:00:00

![seconds no need  to financial from date to date selection](https://user-images.githubusercontent.com/118597994/204454547-bbed0697-48a3-4f08-a0e7-ff847896ef42.png)

**Comment by strategynaveen** [comment]
root cause : actually seconds its showing one the input and change time the seconds is added in  the ui. backend the seconds not considering so its removed

solution : i  just remove the seconds for the from date and to date inputs
