### ISSUE TITLE
Tool changeover is not working

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#49]
When
 I change tool using tool changeover

then
the tools of the following record must change
Actual
tool changeover doesnt occur
![Screenshot (386)](https://user-images.githubusercontent.com/118270248/205023099-dc03acdf-3dce-4c62-a20f-23d6c2f19eeb.png)

**Comment by tamizh061** [comment]
![image](https://user-images.githubusercontent.com/118597994/207578684-c438cb72-7e5a-4125-a698-c4bff66c1c5e.png)
