### ISSUE TITLE
No data occurs in machine 2 5-12-2022 shift A

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#62]
![Screenshot (414)](https://user-images.githubusercontent.com/118270248/205834709-84c9f12f-95eb-422e-9e36-4fcca9620ba2.png)

**Comment by ManikandanS8377** [comment]
![image](https://user-images.githubusercontent.com/80878236/206095834-d6c29869-6acf-471c-8085-77f26e598ee0.png)

**Comment by ManikandanS8377** [comment]
![image](https://user-images.githubusercontent.com/80878236/206096120-19e107ac-1813-4ba3-9dbf-c1d13accdbae.png)
Actually, two different records has created for the particular start time. We will check the root cause

**Comment by ManikandanS8377** [comment]
Root Cause : While handling the offline capability during no data received in MongoDB for that particular hour device status incorrectly handled
Solution : Device status handling logic is changed and fixed

**Comment by DeeruBhai** [comment]
![image](https://user-images.githubusercontent.com/118270248/207596670-602a0cf3-dfd1-4752-8118-dde33bd4ece0.png)
