### ISSUE TITLE
If the tool contain multiple parts, when changing a tool , all parts must be selected automatically

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#63]
When 
i change a tool with multi parts

then
all the parts of that tool ust be selected

Actual
we need to select all parts
![image](https://user-images.githubusercontent.com/118270248/205838735-4302cabd-f531-4f7b-b30b-21d2ef1b50a1.png)

**Comment by strategynaveen** [comment]
root cause : actually this requirement is confirmed by deeraj and shap master mani sir is asking  once tool change all parts are selection parts

solution : the tool dropdown onchange  time its get the mapped parts collection add in dropdown thats time all checkboxes are checked

**Comment by DeeruBhai** [comment]
![image](https://user-images.githubusercontent.com/118270248/207588967-d5df087f-8f74-4c60-bc3e-9a1601e956f3.png)
