### ISSUE TITLE
last updated by time is not updating

### ISSUE THREAD

**Issue by tamizh061** [SmartMach/webapp-v1#69]
![time shown wrongly](https://user-images.githubusercontent.com/118597994/205925298-3f28f7d5-764d-426c-bc80-c95d9ba46703.png)

**Comment by strategynaveen** [comment]
root cause : actually the issue is server side mariadb timezone format is changed the utc format in time 
solution : when i open the server go to the mariadb set session timezone is add +5.30 the normal time zone format is changed
command : SET SESSION time_zone = '+5:30';

**Comment by tamizh061** [comment]
![image](https://user-images.githubusercontent.com/118597994/210511818-8c0bdbd4-dae6-40db-b07a-a1dd1b130312.png)
