### ISSUE TITLE
Default site name is not shown for site admin login

### ISSUE THREAD

**Issue by tamizh061** [SmartMach/webapp-v1#78]
when 
i create new site user
then 
must show site name defaultly 
actual 
does not shown current site name
![image](https://user-images.githubusercontent.com/118597994/206422781-9b054f53-78e0-41ea-bc7f-1302324f13dd.png)
![image](https://user-images.githubusercontent.com/118597994/206422919-081625ec-e077-4039-b21f-8b871460addd.png)

**Comment by strategynaveen** [comment]
root cause : actually the problem is that particular part testing time im working on the database site so thats time im changeing site id for the particular site admin site

solution : then after i call tamil and inform that so thats not issue thats my site fault

**Comment by tamizh061** [comment]
![Uploading image.png…]()
