### ISSUE TITLE
financial oee drill down not shown for site user 

### ISSUE THREAD

**Issue by tamizh061** [SmartMach/webapp-v1#80]
when
i am as a site user gives financial oee drill down view access to site user
then 
must show financial oee drill down to site user
actual
not shown thefinancial oee drill down to site user
![image](https://user-images.githubusercontent.com/118597994/206431155-3b62757d-1ad1-4622-8082-8dbb252feb3a.png)
![WhatsApp Image 2022-12-08 at 4 29 11 PM](https://user-images.githubusercontent.com/118597994/206431347-835b4332-c111-4e98-a52f-4d57e84748f6.jpeg)

**Comment by strategynaveen** [comment]
root cause : actually the problem is graphana home page access control name mismatching for financial_oee_dirllDown this is the correct name but its stored oee_drillDown this name of module not ready.
solution : access control name mismatching
