### ISSUE TITLE
Existng Downtime and quality reasons are not visible in Setting->General module

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#86]
![Screenshot (443)](https://user-images.githubusercontent.com/118270248/206851591-f81a4987-eb18-4a80-89c7-3b4b39cd2da0.png)
![Screenshot (442)](https://user-images.githubusercontent.com/118270248/206851606-ce84083b-39b8-4365-89df-dfa6e13bd5bf.png)
![Screenshot (441)](https://user-images.githubusercontent.com/118270248/206851610-4441ca58-7fe0-42a4-9c96-01c33a1e0885.png)

**Comment by ManikandanS8377** [comment]
This is not a Problem, This happens due copy the S1001(prod) to S1002(demo). 
Root Cause : While import and export database file location is not correctly mapped so that the issuse.
Solution: Rename the downtime & Quality reason file location

**Comment by ManikandanS8377** [comment]
![image](https://user-images.githubusercontent.com/80878236/207518904-71300f95-5960-4fbc-bc3a-acc7ebe3b172.png)

**Comment by ManikandanS8377** [comment]
![image](https://user-images.githubusercontent.com/80878236/207518974-f4029127-25da-4e29-bb15-db0a939b8c9a.png)
